name: testing_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
#  arkit_plugin: ^1.0.7
  arkit_plugin:
    git: https://github.com/olexale/arkit_flutter_plugin.git
  image_picker: ^1.0.7
  permission_handler: ^11.3.0
  image: ^4.1.7
  firebase_core: ^2.27.0
  http: ^1.2.0
  fluttertoast: ^8.2.4
  firebase_storage: ^11.6.9
  cloud_firestore: ^4.15.8
  augmented_reality_plugin: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assest/images/home.png